### ISSUE TITLE
Git Community e definições

### ISSUE THREAD

**Issue by marimendes** [DSW-2018-2/Ticketflix#4]
Elaborar o Git Community, definições de uso do repositório e configurar o git flow.

**Comment by sconetto** [comment]
Coisas a serem feitas:
Mariana
- [x] Descrição do projeto
- [x] Read me (evoluir)
- [x] Contributing
- [x] Licensa

João Pedro 
- [x] Código de Conduta
- [x] Issue template
- [x] Pull Request template
- [x] Guideline de utilização

**Comment by sconetto** [comment]
Terminando algumas definições a configuração do git flow será feita!

**Comment by sconetto** [comment]
feito!
